services:
  app:
    build: .
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    volumes:
      - .:/app
      - ./supervisord_logs:/var/log
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      DEBUG: "1"
      DB_HOST: db
      REDIS_HOST: redis
      CELERY_BROKER_URL: "redis://redis:6379/0"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: Asia/Krasnoyarsk
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./wal_archive:/var/lib/postgresql/wal_archive
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-config.sh

  backup:
    image: postgres:17-alpine
    depends_on:
      - db
    volumes:
      - ./backups:/backups
      - ./backup_scripts:/scripts
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "
      apk add --no-cache postgresql-client &&
      chmod +x /scripts/backup.sh &&
      echo '0 3 * * * /scripts/backup.sh >> /var/log/backup.log 2>&1' > /etc/crontabs/root &&
      crond -l 2 -f
      "
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      
  kodexplorer:
    build:
      context: .
      dockerfile: Dockerfile.kodexplorer
    container_name: kodexplorer
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./uploaded_files:/var/www/html/data/uploaded_files
      - ./convert_and_serve.php:/var/www/html/convert_and_serve.php
      - ./kodexplorer_config:/var/www/html/data/User/admin/home/config
      - kodexplorer_pdf:/tmp/kodexplorer_pdf
    environment:
      - TZ=Asia/Krasnoyarsk
    user: root
    
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    ports:
      - "9980:9980"
    environment:
      - domain=127\\.0\\.0\\.1
      - username=admin
      - password=your_strong_password
      - DONT_GEN_SSL_CERT=yes
    cap_add:
      - MKNOD

volumes:
  postgres_data:
  kodexplorer_pdf: