services:
  app:
    build: .
    volumes:
      - .:/app
      - ./kodexplorer_data/data:/kodexplorer_data/data
      - app_init:/app/init
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SERVICE_TYPE: "app"
      DEBUG: "1"
      DB_HOST: db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      REDIS_HOST: redis
      CELERY_BROKER_URL: "redis://redis:6379/0"
      DJANGO_SETTINGS_MODULE: "archeology.settings"
      MAPS_BASE_URL: "http://nginx-proxy"
      RASTER_TILES_URL: "http://nginx-proxy/raster/{z}/{x}/{y}.png"
      VECTOR_TILES_URL: "http://nginx-proxy/vector/{z}/{x}/{y}.pbf"
    command: bash -c "/app/entrypoint.sh"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 240s
    restart: unless-stopped

  celery-worker:
    build: .
    volumes:
      - .:/app
      - ./supervisord_logs:/var/log
      - app_init:/app/init
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      SERVICE_TYPE: "celery"
      DEBUG: "1"
      DB_HOST: db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      REDIS_HOST: redis
      CELERY_BROKER_URL: "redis://redis:6379/0"
      DJANGO_SETTINGS_MODULE: "archeology.settings"
    command: celery -A archeology worker --loglevel=info --concurrency=4 --logfile -
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "./celery_healthcheck.sh" ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./tiles:/var/www/tiles
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cache:/var/cache/nginx
    depends_on:
      app:
        condition: service_healthy
      tileserver-gl:
        condition: service_started
    restart: unless-stopped

  tileserver-gl:
    image: maptiler/tileserver-gl
    volumes:
      - ./tiles/vector:/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  db:
    image: postgres:17
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: Asia/Krasnoyarsk
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./wal_archive:/var/lib/postgresql/wal_archive
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-config.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backup:
    image: postgres:17-alpine
    depends_on:
      - db
    volumes:
      - ./backups:/backups
      - ./backup_scripts:/scripts
      - postgres_data_test:/var/lib/postgresql/data-test
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "
      apk add --no-cache postgresql-client &&
      chmod +x /scripts/backup.sh &&
      echo '0 3 * * * /scripts/backup.sh >> /var/log/backup.log 2>&1' > /etc/crontabs/root &&
      crond -l 2 -f
      "
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  kodexplorer:
    build:
      context: .
      dockerfile: Dockerfile.kodexplorer
    container_name: kodexplorer
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # - ./kodexplorer_config:/var/www/html/data/User/admin/home/config
      - ./kodexplorer_data/data:/var/www/html/data
      - ./uploaded_files:/var/www/html/data/uploaded_files
      - type: bind
        source: ./kodexplorer_data/officeLive
        target: /var/www/html/plugins/officeLive
        read_only: true
    environment:
      - TZ=Asia/Krasnoyarsk
    user: root

  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    ports:
      - "9980:9980"
    environment:
      - aliasgroup1=http://app:8000
      - username=admin
      - password=admin
      - DONT_GEN_SSL_CERT=yes
      - extra_params=--o:ssl.enable=false --o:storage.wopi.host.allowlist=localhost,127.0.0.1,app,host.docker.internal
      - dictionaries=ru en_US
      - LANGUAGE=ru_RU.UTF-8
    cap_add:
      - MKNOD

volumes:
  postgres_data:
  postgres_data_test:
  app_init: