python.exe -m pip install --upgrade pip
pip install psycopg2-binary
pip install psycopg2
pip install psycopg2==2.9.10
pip install pyKE
pip install pyKE==0.5.1
pip install xformers
pip install xformers==0.0.20
pip install torch
pip install torch==2.5.1+cu124
pip install torchaudio
pip install torchaudio==2.5.1+cu124
pip install tokenizers
pip install tokenizers==0.21.0
pip install autorag
pip install duckduckgo_search
pip install duckduckgo_search==7.3.0
pip install click
pip install click==8.1.7
pip install transformers
pip install transformers==4.47.1
pip install huggingface-hub
pip install huggingface-hub==0.27.0
pip install llama-index-llms-huggingface
pip install llama-index-llms-huggingface==0.3.5
pip install greenlet
pip install greenlet==3.1.1
pip install playwright
pip install playwright==1.43.0
pip install vllm
pip install vllm==0.6.6
pip install openvino
pip install openvino==2024.6.0
pip install openvino-telemetry
pip install openvino-telemetry==2024.5.0
pip install openvino-tokenizers
pip install openvino-tokenizers==2024.6.0.0
pip install Django==5.1.2
pip install Django-Accounts==0.1
pip install django-celery-results==2.5.1
pip install django-cors-headers==4.6.0
pip install django-crispy-forms==2.3
pip install django-nested-inline==0.4.6
pip install djangorestframework==3.15.2