[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:web]
command=python manage.py runserver 0.0.0.0:8000
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr  ;/var/log/web.err.log
stdout_logfile=/dev/stdout  ;/var/log/web.out.log
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:celery]
command=celery -A archeology worker --loglevel=info -P eventlet
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stderr  ;/var/log/celery.err.log
stdout_logfile=/dev/stdout  ;/var/log/celery.out.log
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0