from django.urls import path, include

from agregator import views
from rest_framework.routers import DefaultRouter
from agregator.wopi import views as wopi_views
from agregator.wopi.views import kodexplorer_proxy
from agregator.views import datatable_views
from django.views.decorators.http import require_http_methods

router = DefaultRouter()

urlpatterns = [
    path('health/', views.health_check, name='health'),
    path('', views.auth.index, name='index'),
    path('deconstructor/', views.file_processing.deconstructor, name='deconstructor'),
    path('external_sources/', views.file_processing.external_sources, name='external_sources'),
    path('api/check_external_scan_progress/<str:task_id>/',
         views.file_processing.check_external_scan_progress,
         name='check_external_scan_progress'),
    path('api/cancel_external_scan_task/<str:task_id>/', views.file_processing.cancel_external_scan_task,
         name='cancel_external_scan_task'),
    path('interactive_map/', views.interactive_map, name='interactive_map'),
    path('acts_register/', views.registers.acts_register, name='acts_register'),
    path('acts_register_download/', views.registers.acts_register_download,
         name='acts_register_download'),
    path('open_list_ocr/', views.file_processing.open_list_ocr, name='open_list_ocr'),
    path('open_lists_register/', views.registers.open_lists_register, name='open_lists_register'),
    path('open_lists_register_download/', views.registers.open_lists_register_download,
         name='open_lists_register_download'),
    path('scientific_reports_register/', views.registers.scientific_reports_register,
         name='scientific_reports_register'),
    path('scientific_reports_register_download/', views.registers.scientific_reports_register_download,
         name='scientific_reports_register_download'),
    path('tech_reports_register/', views.registers.tech_reports_register, name='tech_reports_register'),
    path('tech_reports_register_download/', views.registers.tech_reports_register_download,
         name='tech_reports_register_download'),
    path('archaeological_heritage_sites_register/', views.registers.archaeological_heritage_sites_register,
         name='archaeological_heritage_sites_register'),
    path('archaeological_heritage_sites_download/',
         views.registers.archaeological_heritage_sites_download,
         name='archaeological_heritage_sites_download'),
    path('identified_archaeological_heritage_sites_register/',
         views.registers.identified_archaeological_heritage_sites_register,
         name='identified_archaeological_heritage_sites_register'),
    path('identified_archaeological_heritage_sites_download/',
         views.registers.identified_archaeological_heritage_sites_download,
         name='identified_archaeological_heritage_sites_download'),
    path('account_cards_upload/', views.file_processing.account_cards_upload, name='account_cards_upload'),
    path('account_cards_register/', views.registers.account_cards_register,
         name='account_cards_register'),
    path('account_cards_register_download/', views.registers.account_cards_register_download,
         name='account_cards_register_download'),
    path('commercial_offers_upload/', views.file_processing.commercial_offers_upload,
         name='commercial_offers_upload'),
    path('commercial_offers_register/', views.registers.commercial_offers_register,
         name='commercial_offers_register'),
    path('geo_objects_upload/', views.file_processing.geo_objects_upload, name='geo_objects_upload'),
    path('geo_objects_register/', views.registers.geo_objects_register, name='geo_objects_register'),
    path('gpt_chat/', views.gpt_chat, name='gpt_chat'),
    path('create_gpt_chat/', views.create_gpt_chat, name='create_gpt_chat'),
    path('edit_gpt_chat/', views.edit_gpt_chat, name='edit_gpt_chat'),
    path('delete_gpt_chat/', views.delete_gpt_chat, name='delete_gpt_chat'),
    path('ask_gpt/', views.ask_gpt, name='ask_gpt'),
    path('edit_chat_message/', views.edit_chat_message, name='edit_chat_message'),
    path('delete_chat_message/', views.delete_chat_message, name='delete_chat_message'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings, name='settings'),

    path('users/<int:pk>/', views.users, name='users'),
    path('acts/<int:pk>/', views.acts, name='acts'),
    path('acts_edit/<int:pk>/', views.acts_edit, name='acts_edit'),
    path('acts_delete/<int:pk>/', views.acts_delete, name='acts_delete'),
    path('scientific_reports/<int:pk>/', views.scientific_reports,
         name='scientific_reports'),
    path('scientific_reports_edit/<int:pk>/', views.scientific_reports_edit,
         name='scientific_reports_edit'),
    path('scientific_reports_delete/<int:pk>/', views.scientific_reports_delete,
         name='scientific_reports_delete'),
    path('tech_reports/<int:pk>/', views.tech_reports, name='tech_reports'),
    path('tech_reports_edit/<int:pk>/', views.tech_reports_edit, name='tech_reports_edit'),
    path('tech_reports_delete/<int:pk>/', views.tech_reports_delete,
         name='tech_reports_delete'),
    path('doc_reprocess/<int:pk>/', views.doc_reprocess, name='doc_reprocess'),
    path('open_lists/<int:pk>/', views.open_lists, name='open_lists'),
    path('open_lists_edit/<int:pk>/', views.open_lists_edit, name='open_lists_edit'),
    path('open_lists_delete/<int:pk>/', views.open_lists_delete, name='open_lists_delete'),
    path('map/<str:report_type>/<int:pk>/', views.map, name='map'),
    path('map/<str:report_type>/<int:pk>/download/', views.download_coordinates,
         name='download_coordinates'),
    path('interactive_map/download/', views.download_all_coordinates,
         name='download_all_coordinates'),
    path('account_cards/<int:pk>/', views.account_cards, name='account_cards'),
    path('account_cards_edit/<int:pk>/', views.account_cards_edit, name='account_cards_edit'),
    path('account_cards_delete/<int:pk>/', views.account_cards_delete,
         name='account_cards_delete'),
    path('archaeological_heritage_sites/<int:pk>/', views.archaeological_heritage_sites,
         name='archaeological_heritage_sites'),
    path('archaeological_heritage_sites_edit/<int:pk>/',
         views.archaeological_heritage_sites_edit,
         name='archaeological_heritage_sites_edit'),
    path('archaeological_heritage_sites_delete/<int:pk>/',
         views.archaeological_heritage_sites_delete,
         name='archaeological_heritage_sites_delete'),
    path('identified_archaeological_heritage_sites/<int:pk>/',
         views.identified_archaeological_heritage_sites,
         name='identified_archaeological_heritage_sites'),
    path('identified_archaeological_heritage_sites_edit/<int:pk>/',
         views.identified_archaeological_heritage_sites_edit,
         name='identified_archaeological_heritage_sites_edit'),
    path('identified_archaeological_heritage_sites_delete/<int:pk>/',
         views.identified_archaeological_heritage_sites_delete,
         name='identified_archaeological_heritage_sites_delete'),
    path('commercial_offers_edit/<int:pk>/', views.commercial_offers_edit,
         name='commercial_offers_edit'),
    path('commercial_offers_delete/<int:pk>/', views.commercial_offers_delete,
         name='commercial_offers_delete'),
    path('download_commercial_offer_report/<int:pk>/', views.download_commercial_offer_report,
         name='download_commercial_offer_report'),
    path('geo_objects_edit/<int:pk>/', views.geo_objects_edit, name='geo_objects_edit'),
    path('geo_objects_delete/<int:pk>/', views.geo_objects_delete, name='geo_objects_delete'),

    path('batch/', views.batch_processing_dashboard, name='batch_processing'),
    path('batch/scan/', views.scan_directory, name='batch_scan'),
    path('batch/process/', views.process_batch_files, name='batch_process'),

    path('api/download_delete/<str:task_id>/', views.download_delete, name='download_delete'),
    path('api/get_user_tasks_reports/', views.get_user_tasks_reports,
         name='get_user_tasks_reports'),
    path('api/get_user_tasks_open_lists/', views.get_user_tasks_open_lists,
         name='get_user_tasks_open_lists'),
    path('api/get_user_tasks_external/', views.get_user_tasks_external,
         name='get_user_tasks_external'),
    path('api/get_user_tasks_object_account_cards/', views.get_user_tasks_object_account_cards,
         name='get_user_tasks_object_account_cards'),
    path('api/get_user_tasks_commercial_offers/', views.get_user_tasks_commercial_offers,
         name='get_user_tasks_commercial_offers'),
    path('api/get_user_tasks_geo_objects/', views.get_user_tasks_geo_objects,
         name='get_user_tasks_geo_objects'),
    path('api/get_geojson_polygons/', views.get_geojson_polygons, name='get_geojson_polygons'),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('api/users/', views.UserList.as_view(), name='user-list'),
    path('api/users/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),

    path('api/acts/', views.ActList.as_view(), name='act-list'),
    path('api/acts/<int:pk>/', views.ActDetail.as_view(), name='act-detail'),

    path('api/scientific_reports/', views.ScientificReportList.as_view(), name='scientificreport-list'),
    path('api/scientific_reports/<int:pk>/', views.ScientificReportDetail.as_view(),
         name='scientificreport-detail'),

    path('api/tech_reports/', views.TechReportList.as_view(), name='techreport-list'),
    path('api/tech_reports/<int:pk>/', views.TechReportDetail.as_view(), name='techreport-detail'),

    path('api/open_lists/', views.OpenListsList.as_view(), name='openlists-list'),
    path('api/open_lists/<int:pk>/', views.OpenListsDetail.as_view(), name='openlists-detail'),

    path('api/archaeological_heritage_sites/', views.ArchaeologicalHeritageSiteList.as_view(),
         name='archaeologicalheritagesite-list'),
    path('api/archaeological_heritage_sites/<int:pk>/', views.ArchaeologicalHeritageSiteDetail.as_view(),
         name='archaeologicalheritagesite-detail'),

    path('api/identified_archaeological_heritage_sites/', views.IdentifiedArchaeologicalHeritageSiteList.as_view(),
         name='identifiedarchaeologicalheritagesite-list'),
    path('api/identified_archaeological_heritage_sites/<int:pk>/',
         views.IdentifiedArchaeologicalHeritageSiteDetail.as_view(),
         name='identifiedarchaeologicalheritagesite-detail'),

    path('api/object_account_cards/', views.ObjectAccountCardList.as_view(), name='objectaccountcard-list'),
    path('api/object_account_cards/<int:pk>/', views.ObjectAccountCardDetail.as_view(),
         name='objectaccountcard-detail'),

    path('api/commercial_offers/', views.CommercialOffersList.as_view(), name='commercialoffers-list'),
    path('api/commercial_offers/<int:pk>/', views.CommercialOffersDetail.as_view(), name='commercialoffers-detail'),

    path('api/geo_objects/', views.GeoObjectList.as_view(), name='geoobject-list'),
    path('api/geo_objects/<int:pk>/', views.GeoObjectDetail.as_view(), name='geoobject-detail'),

    path('api/geojson_data/', views.GeojsonDataList.as_view(), name='geojsondata-list'),
    path('api/geojson_data/<int:pk>/', views.GeojsonDataDetail.as_view(), name='geojsondata-detail'),

    path('api/chats/', views.ChatList.as_view(), name='chat-list'),
    path('api/chats/<int:pk>/', views.ChatDetail.as_view(), name='chat-detail'),

    path('api/messages/', views.MessageList.as_view(), name='message-list'),
    path('api/messages/<int:pk>/', views.MessageDetail.as_view(), name='message-detail'),

    # WOPI API endpoints
    path('wopi/files/<path:file_id>/contents', wopi_views.wopi_contents, name='wopi_contents'),
    path('wopi/files/<path:file_id>', wopi_views.wopi_endpoint, name='wopi_endpoint'),
    path('kodexplorer-proxy/', kodexplorer_proxy, name='kodexplorer_proxy'),

    # DataTables API endpoints
    path('api/archaeological_heritage_sites_datatable/',
         datatable_views.universal_datatable,
         {'register_type': 'archaeological'},
         name='archaeological_heritage_sites_datatable'),
    path('api/identified_archaeological_heritage_sites_datatable/',
         datatable_views.universal_datatable,
         {'register_type': 'identified'},
         name='identified_archaeological_heritage_sites_datatable'),
    path('api/acts_datatable/',
         datatable_views.universal_datatable,
         {'register_type': 'acts'},
         name='acts_datatable'),
    path('api/scientific_reports_datatable/', datatable_views.universal_datatable,
         {'register_type': 'scientific_reports'},
         name='scientific_reports_datatable'),
    path('api/tech_reports_datatable/', datatable_views.universal_datatable, {'register_type': 'tech_reports'},
         name='tech_reports_datatable'),
    path('api/open_lists_datatable/', datatable_views.universal_datatable,
         {'register_type': 'open_lists'}, name='open_lists_datatable'),
    path('api/account_cards_datatable/', datatable_views.universal_datatable,
         {'register_type': 'account_cards'}, name='account_cards_datatable'),
    path('api/commercial_offers_datatable/', datatable_views.universal_datatable,
         {'register_type': 'commercial_offers'}, name='commercial_offers_datatable'),
    path('api/geo_objects_datatable/', datatable_views.universal_datatable,
         {'register_type': 'geo_objects'}, name='geo_objects_datatable'),
]
