# Generated by Django 5.1.2 on 2025-04-21 07:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="avatars/default.png", upload_to="avatars/"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("upload_source", models.JSONField(blank=True, null=True)),
                ("is_processing", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("year", models.TextField()),
                ("finish_date", models.TextField()),
                ("type", models.TextField()),
                ("name_number", models.TextField()),
                ("place", models.TextField()),
                ("customer", models.TextField()),
                ("area", models.TextField()),
                ("expert", models.TextField()),
                ("executioner", models.TextField()),
                ("open_list", models.TextField()),
                ("conclusion", models.TextField()),
                ("border_objects", models.TextField()),
                ("source", models.JSONField(blank=True, null=True)),
                ("act", models.TextField()),
                ("start_date", models.TextField()),
                ("exp_place", models.TextField()),
                ("exp_customer", models.TextField()),
                ("exp_expert", models.TextField()),
                ("relationship", models.TextField()),
                ("goal", models.TextField()),
                ("object", models.TextField()),
                ("docs", models.TextField()),
                ("exp_info", models.TextField()),
                ("exp_facts", models.TextField()),
                ("literature", models.TextField()),
                ("exp_conclusion", models.TextField()),
                ("supplement", models.JSONField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acts",
            },
        ),
        migrations.CreateModel(
            name="ObjectAccountCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("upload_source", models.JSONField(blank=True, null=True)),
                ("is_processing", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("origin_filename", models.TextField()),
                ("name", models.TextField()),
                ("creation_time", models.TextField()),
                ("address", models.TextField()),
                ("object_type", models.TextField()),
                ("general_classification", models.TextField()),
                ("description", models.TextField()),
                ("usage", models.TextField()),
                ("discovery_info", models.TextField()),
                ("compiler", models.TextField()),
                ("supplement", models.JSONField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "object_account_cards",
            },
        ),
        migrations.CreateModel(
            name="IdentifiedArchaeologicalHeritageSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("obj_info", models.TextField(blank=True, null=True)),
                ("document", models.TextField(blank=True, null=True)),
                ("is_excluded", models.BooleanField(default=False)),
                (
                    "account_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agregator.objectaccountcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выявленный археологический объект культурного наследия",
                "verbose_name_plural": "Выявленные археологические объекты культурного наследия",
                "db_table": "identified_archaeological_heritage_sites",
            },
        ),
        migrations.CreateModel(
            name="ArchaeologicalHeritageSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("doc_name", models.TextField(blank=True, null=True)),
                ("district", models.TextField(blank=True, null=True)),
                ("document", models.TextField(blank=True, null=True)),
                ("register_num", models.TextField(blank=True, null=True)),
                ("is_excluded", models.BooleanField(default=False)),
                (
                    "account_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agregator.objectaccountcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Археологический объект культурного наследия",
                "verbose_name_plural": "Археологические объекты культурного наследия",
                "db_table": "archaeological_heritage_sites",
            },
        ),
        migrations.CreateModel(
            name="OpenLists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_filename", models.TextField()),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("upload_source", models.JSONField(blank=True, null=True)),
                ("is_processing", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("number", models.TextField()),
                ("holder", models.TextField()),
                ("object", models.TextField()),
                ("works", models.TextField()),
                ("start_date", models.TextField()),
                ("end_date", models.TextField()),
                ("source", models.FileField(upload_to="open_lists/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "open_lists",
            },
        ),
        migrations.CreateModel(
            name="ScientificReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("upload_source", models.JSONField(blank=True, null=True)),
                ("is_processing", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.TextField()),
                ("organization", models.TextField()),
                ("author", models.TextField()),
                ("open_list", models.TextField()),
                ("writing_date", models.TextField()),
                ("introduction", models.TextField()),
                ("contractors", models.TextField()),
                ("place", models.TextField()),
                ("area_info", models.TextField()),
                ("research_history", models.TextField()),
                ("results", models.TextField()),
                ("conclusion", models.TextField()),
                ("source", models.JSONField(blank=True, null=True)),
                ("content", models.JSONField(blank=True, null=True)),
                ("supplement", models.JSONField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scientific_reports",
            },
        ),
        migrations.CreateModel(
            name="TechReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("upload_source", models.JSONField(blank=True, null=True)),
                ("is_processing", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("name", models.TextField()),
                ("organization", models.TextField()),
                ("author", models.TextField()),
                ("open_list", models.TextField()),
                ("writing_date", models.TextField()),
                ("introduction", models.TextField()),
                ("contractors", models.TextField()),
                ("place", models.TextField()),
                ("area_info", models.TextField()),
                ("research_history", models.TextField()),
                ("results", models.TextField()),
                ("conclusion", models.TextField()),
                ("source", models.JSONField(blank=True, null=True)),
                ("content", models.JSONField(blank=True, null=True)),
                ("supplement", models.JSONField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tech_reports",
            },
        ),
        migrations.CreateModel(
            name="UserTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255)),
                ("files_type", models.CharField(max_length=255)),
                ("upload_source", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_tasks",
            },
        ),
    ]
