# Generated by Django 5.1.2 on 2025-01-04 10:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps', models.TextField()),
                ('object_fotos', models.TextField()),
                ('pits_fotos', models.TextField()),
                ('plans', models.TextField()),
                ('material_fotos', models.TextField()),
                ('heritage_info', models.TextField()),
            ],
            options={
                'db_table': 'supplements',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OpenLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('holder', models.TextField()),
                ('object', models.TextField()),
                ('works', models.TextField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('source', models.FileField(upload_to='open_lists/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'open_lists',
            },
        ),
        migrations.CreateModel(
            name='ScientificReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organization', models.TextField()),
                ('author', models.TextField()),
                ('open_list', models.TextField()),
                ('writing_date', models.TextField()),
                ('introduction', models.TextField()),
                ('contractors', models.TextField()),
                ('place', models.TextField()),
                ('area_info', models.TextField()),
                ('research_history', models.TextField()),
                ('results', models.TextField()),
                ('conclusion', models.TextField()),
                ('source', models.FileField(upload_to='reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agregator.supplement')),
            ],
            options={
                'db_table': 'scientific_reports',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('finish_date', models.TextField()),
                ('type', models.TextField()),
                ('name_number', models.TextField()),
                ('place', models.TextField()),
                ('customer', models.TextField()),
                ('area', models.TextField()),
                ('expert', models.TextField()),
                ('executioner', models.TextField()),
                ('open_list', models.TextField()),
                ('conclusion', models.TextField()),
                ('border_objects', models.TextField()),
                ('source', models.FileField(upload_to='acts/')),
                ('act', models.TextField()),
                ('start_date', models.TextField()),
                ('exp_place', models.TextField()),
                ('exp_customer', models.TextField()),
                ('exp_expert', models.TextField()),
                ('relationship', models.TextField()),
                ('goal', models.TextField()),
                ('object', models.TextField()),
                ('docs', models.TextField()),
                ('exp_info', models.TextField()),
                ('exp_facts', models.TextField()),
                ('literature', models.TextField()),
                ('exp_conclusion', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agregator.supplement')),
            ],
            options={
                'db_table': 'acts',
            },
        ),
        migrations.CreateModel(
            name='TechReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('organization', models.TextField()),
                ('author', models.TextField()),
                ('open_list', models.TextField()),
                ('writing_date', models.TextField()),
                ('introduction', models.TextField()),
                ('contractors', models.TextField()),
                ('place', models.TextField()),
                ('area_info', models.TextField()),
                ('research_history', models.TextField()),
                ('results', models.TextField()),
                ('conclusion', models.TextField()),
                ('source', models.FileField(upload_to='reports/')),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agregator.supplement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tech_reports',
            },
        ),
    ]
