# Generated by Django 5.1.2 on 2025-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasks',
            name='files_type',
            field=models.CharField(default='acts', max_length=255),
            preserve_default=False,
        ),
    ]
