events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream tileserver {
        server tileserver-gl:8080;
    }

    upstream django_app {
        server app:8000;
    }

    sendfile on;
    keepalive_timeout 65;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log;

    server {
        listen 80;
        server_name _;

        # Static raster tiles
        location ~ ^/raster/(?<map_name>[^/]+)/(?<z>\d+)/(?<x>\d+)/(?<y>\d+)\.png$ {
            root /var/www;
            try_files /$map_name/$z/$x/$y.png =404;
            autoindex off;
            add_header Access-Control-Allow-Origin "*" always;
            add_header Cache-Control "public, max-age=31536000, immutable";
            expires 1y;
        }
        
        location /raster/ {
            return 403;
        }

        location /vector/ {
			# НЕ ИСПОЛЬЗУЕМ rewrite - сохраняем полный путь
			proxy_pass http://tileserver/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

        # Main Django application for all other requests
        location / {
            proxy_pass http://django_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}